name: fit_track_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  badges: ^3.1.2
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview_plus: ^2.3.4
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7+1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_svg_provider: ^1.0.7
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  lottie: ^3.3.1
  persistent_bottom_nav_bar: ^6.2.1
  pretty_dio_logger: ^1.4.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
  #   - images/a_dot_ham.jpeg
